# Generated by Django 5.2.7 on 2025-10-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_productmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
