# Generated by Django 5.2.7 on 2025-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_productmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
