# Generated by Django 5.2.7 on 2025-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_productmodel_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
