# Generated by Django 5.2.7 on 2025-10-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_productmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
