# Generated by Django 5.2.7 on 2025-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_productmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='عنوان در مرورگر'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='text',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه'),
        ),
    ]
