# Generated by Django 5.2.7 on 2025-10-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_productmodel_options_productmodel_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='auction',
            field=models.BooleanField(default=False, verbose_name='حراج'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='عنوان در مرورگر'),
        ),
    ]
