# Generated by Django 5.2.7 on 2025-10-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_productmodel_auction_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد موجودی'),
        ),
    ]
