# Generated by Django 5.2.7 on 2025-10-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_color_alter_category_options_productmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(related_name='colors', to='product_app.color', verbose_name='رنگ بندی'),
        ),
    ]
