# Generated by Django 5.2.7 on 2025-11-10 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact')),
                ('full_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='max length invalid must 50 character')])),
                ('email', models.EmailField(help_text='ایمیل کاربر', max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'pending message'), ('READ', 'read message'), ('RESPONDED', 'responded message')], default='PENDING', max_length=50)),
                ('response', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
